name: andgarivara
description: Want to have a safe,secure & comfortable journey? Andgarivara is here for you Featuring instant ride, ride sharing, rent a car ,car leasing and much more.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #UI/UX
  intro_slider: ^2.3.3
  flutter_signin_button: ^1.1.0
  loading_overlay: ^0.2.1
  flutter_spinkit: ^4.1.2
  cached_network_image: ^2.3.3
  flutter_launcher_icons: ^0.8.1
  pinput: ^0.2.6
  flutter_dotenv: ^2.1.0
  flutter_svg: ^0.19.1
  flutter_swiper: ^1.1.6
  flutter_simple_rating_bar: ^0.0.3
  intl: any
  awesome_dialog: ^1.2.1
  ticketview: ^1.0.0

  #Map
  google_maps_flutter: ^1.0.6
  permission: ^0.1.7
  geolocator: ^6.1.7
  geocoder: ^0.2.1
  flutter_polyline_points: ^0.2.4


  #GetX
  get: ^3.17.1
  get_storage: ^1.3.2

  #payment
  #braintree_payment: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo/app_logo.png"
  adaptive_icon_background: '#C8102E'
  fill: true
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/svg/
    - assets/images/intro/
    - assets/images/appLogo/
    - assets/demo/
    - assets/icons/

  fonts:
    - family: Roboto-R
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-M
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family:  TicketIcon
      fonts:
       - asset: assets/icons/TicketIcon.ttf
